name: JobUI-xsoap
main: xjob\economyjob\EconomyJob
version: TWICE
api: 
- 1.0.0
- 1.1.0
- 1.2.0
- 1.2.1
- 1.3.0
- 1.3.1
- 1.4.0
- 3.0.0
- 4.0.0

author: onebone, XSOAP

commands:
 job:
  description: JobUI By xSoap
  usage: /job <join|retire|list|me>
  permission: economyjob.command.job
permissions:
 economyjob.command.*:
  description: Allows player to use all of job command
  default: op
  children:
   economyjob.command.job:
    description: Allows player to use /job command
    default: true
    children:
     economyjob.command.job.join:
      description: Allows player to use command that allows to join job
      default: true
     economyjob.command.job.retire:
      description: Allows player to use command that allows to retire job
      default: true
     economyjob.command.job.list:
      description: Allows player to use command that allows to see job list
      default: true
     economyjob.command.job.me:
      description: Allows player to use command that allows to see its job
